In [5]:
import yaml
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
teams_df = pd.read_csv('../models/teams_EM.csv')
teams_df

,Unnamed: 0,Team,7mPGoals,7mPMissed,6mCGoals,6mCMissed,WingGoals,WingMissed,BTGoals,BTMissed,...,2M,AS,R7,ST,BS,P7,TO,PC1,PC2,cluster
0,0,CRO,16,7,49,12,41,32,20,4,...,28,96,25,33,15,42,98,-3.007976,4.226142,3
1,1,CZE,8,5,4,3,22,10,5,3,...,10,22,13,12,3,24,40,5.047346,0.364696,0
2,2,DEN,20,7,23,15,75,39,21,5,...,25,94,27,39,29,32,84,-3.174269,0.759901,3
3,3,ESP,26,5,24,16,50,39,5,11,...,24,83,31,24,10,21,94,-0.934444,-0.324208,1
4,4,FRA,21,11,36,24,56,34,17,4,...,26,90,32,55,20,34,96,-4.118907,1.369064,3
5,5,GER,15,12,24,12,32,27,22,14,...,27,76,27,26,13,30,72,-1.206175,0.056285,1
6,6,HUN,17,6,14,10,46,36,25,13,...,13,80,24,23,11,25,79,-0.210540,-1.356587,4
7,7,MNE,20,3,25,5,44,47,4,6,...,17,77,23,28,8,20,77,0.477307,-1.030249,4
8,8,NED,21,7,29,8,51,49,23,16,...,22,105,28,34,15,23,81,-2.727188,-1.817280,1
9,9,NOR,35,9,36,14,59,40,44,15,...,18,148,44,34,33,24,75,-5.388616,-3.702451,2
10,10,POL,9,2,10,2,15,10,7,4,...,12,37,11,11,12,12,44,5.198268,-0.543011,0
11,11,ROU,14,6,30,8,30,34,12,6,...,17,72,20,10,7,20,92,0.652334,0.527256,4
12,12,RUS,15,6,28,6,62,33,23,6,...,24,81,21,30,12,28,78,-1.043192,0.002938,1
13,13,SLO,5,5,10,10,18,18,3,1,...,12,23,10,11,0,10,30,5.650701,0.524214,0
14,14,SRB,10,4,15,5,30,21,6,5,...,7,46,14,13,4,8,38,5.047540,-1.176434,0
15,15,SWE,18,13,34,13,32,25,12,3,...,22,75,31,18,8,27,84,-0.262189,2.119723,1

In [6]:
with open('../data/matches.yml', 'r', encoding='utf8') as f:
    matches = yaml.safe_load(f)

In [8]:
def country_abbr(country_name):
    return {
        'Alemania': 'GER',
        'Croacia': 'CRO',
        'Dinamarca': 'DEN',
        'Eslovenia': 'SLO',
        'España': 'ESP',
        'Francia': 'FRA',
        'Hungría': 'HUN',
        'Montenegro': 'MNE',
        'Noruega': 'NOR',
        'Países Bajos': 'NED',
        'Polonia': 'POL',
        'República Checa': 'CZE',
        'Rumania': 'ROU',
        'Rusia': 'RUS',
        'Serbia': 'SRB',
        'Suecia': 'SWE'
    }[country_name]

In [15]:
train_matches = []
test_matches = []
for phase in matches:
    for group in matches[phase]:
        for match in matches[phase][group]:
            teamA, teamB = match.keys()
            
            if match[teamA] == match[teamB]:
                winner = 'tie'
            else:
                winner = 'first' if match[teamA] > match[teamB] else 'second'

            if phase == 'first':
                test_matches.append([country_abbr(teamA), country_abbr(teamB), winner])
            else:
                train_matches.append([country_abbr(teamA), country_abbr(teamB), winner])
            
print("Train:", train_matches)
print()
print("Test:", test_matches)

Train: [['MNE', 'RUS', 'second'], ['FRA', 'ESP', 'first'], ['FRA', 'RUS', 'tie'], ['DEN', 'SWE', 'first'], ['MNE', 'SWE', 'first'], ['DEN', 'ESP', 'first'], ['MNE', 'ESP', 'tie'], ['FRA', 'SWE', 'first'], ['DEN', 'RUS', 'first'], ['CRO', 'ROU', 'first'], ['NED', 'NOR', 'second'], ['HUN', 'GER', 'second'], ['CRO', 'NOR', 'second'], ['NED', 'GER', 'first'], ['HUN', 'ROU', 'first'], ['NED', 'ROU', 'first'], ['CRO', 'GER', 'first'], ['HUN', 'NOR', 'second'], ['RUS', 'NED', 'first'], ['FRA', 'CRO', 'first'], ['NOR', 'DEN', 'first'], ['CRO', 'DEN', 'first'], ['FRA', 'NOR', 'second']]

Test: [['FRA', 'MNE', 'first'], ['DEN', 'SLO', 'first'], ['SLO', 'FRA', 'second'], ['MNE', 'DEN', 'second'], ['MNE', 'SLO', 'first'], ['FRA', 'DEN', 'first'], ['RUS', 'ESP', 'first'], ['SWE', 'CZE', 'first'], ['CZE', 'RUS', 'second'], ['ESP', 'SWE', 'tie'], ['ESP', 'CZE', 'first'], ['RUS', 'SWE', 'first'], ['HUN', 'CRO', 'second'], ['NED', 'SRB', 'second'], ['SRB', 'HUN', 'second'], ['CRO', 'NED', 'first'], ['SRB', 'CRO', 'second'], ['NED', 'HUN', 'first'], ['ROU', 'GER', 'second'], ['NOR', 'POL', 'first'], ['POL', 'ROU', 'second'], ['GER', 'NOR', 'second'], ['GER', 'POL', 'tie'], ['ROU', 'NOR', 'second']]

In [16]:
#team_features = ['7mPGoals', '7mPMissed', '6mCGoals', '6mCMissed', 'WingGoals', 'WingMissed', 'BTGoals', 'BTMissed', 'FBGoals', 'FBMissed', 'FTOGoals', 'FTOMissed', '9mGoals', '9mMissed', 'RC', '2M', 'AS', 'R7', 'ST', 'BS', 'P7', 'TO', 'PC1', 'PC2', 'cluster']
team_features = ['7mPGoals', '7mPMissed', '6mCGoals', '6mCMissed', 'WingGoals', 'WingMissed', 'BTGoals', 'BTMissed', 'FBGoals', 'FBMissed', 'FTOGoals', 'FTOMissed', '9mGoals', '9mMissed', 'RC', '2M', 'AS', 'R7', 'ST', 'BS', 'P7', 'TO', 'cluster']

match_features = [*[f'A_{f}' for f in team_features], *[f'B_{f}' for f in team_features]]

def generate_data(matches, teams_df, augment=False):
    data = []
    for match in matches:
        if len(match) == 3:
            teamA, teamB, result = match
        elif len(match) == 2:
            teamA, teamB = match
            result = None
        
        teamA_data = teams_df.loc[teams_df['Team'] == teamA][team_features].values.tolist()[0]
        teamB_data = teams_df.loc[teams_df['Team'] == teamB][team_features].values.tolist()[0]
        
        data.append([teamA, teamB, *teamA_data, *teamB_data, result])
        if augment:
            data.append([
                teamB, teamA,
                *teamB_data, *teamA_data,
                {None:None, 'tie': 'tie', 'first': 'second', 'second': 'first'}[result]
            ])
    
    return pd.DataFrame(data=data,
                        columns=['teamA', 'teamB', *match_features, 'result'])

In [17]:
train_df = generate_data(train_matches, teams_df, augment=True)
test_df = generate_data(test_matches, teams_df)

train_df

,teamA,teamB,A_7mPGoals,A_7mPMissed,A_6mCGoals,A_6mCMissed,A_WingGoals,A_WingMissed,A_BTGoals,A_BTMissed,...,B_RC,B_2M,B_AS,B_R7,B_ST,B_BS,B_P7,B_TO,B_cluster,result
0,MNE,RUS,20,3,25,5,44,47,4,6,...,0,24,81,21,30,12,28,78,1,second
1,RUS,MNE,15,6,28,6,62,33,23,6,...,0,17,77,23,28,8,20,77,4,first
2,FRA,ESP,21,11,36,24,56,34,17,4,...,1,24,83,31,24,10,21,94,1,first
3,ESP,FRA,26,5,24,16,50,39,5,11,...,1,26,90,32,55,20,34,96,3,second
4,FRA,RUS,21,11,36,24,56,34,17,4,...,0,24,81,21,30,12,28,78,1,tie
5,RUS,FRA,15,6,28,6,62,33,23,6,...,1,26,90,32,55,20,34,96,3,tie
6,DEN,SWE,20,7,23,15,75,39,21,5,...,0,22,75,31,18,8,27,84,1,first
7,SWE,DEN,18,13,34,13,32,25,12,3,...,0,25,94,27,39,29,32,84,3,second
8,MNE,SWE,20,3,25,5,44,47,4,6,...,0,22,75,31,18,8,27,84,1,first
9,SWE,MNE,18,13,34,13,32,25,12,3,...,0,17,77,23,28,8,20,77,4,second
10,DEN,ESP,20,7,23,15,75,39,21,5,...,1,24,83,31,24,10,21,94,1,first
11,ESP,DEN,26,5,24,16,50,39,5,11,...,0,25,94,27,39,29,32,84,3,second
12,MNE,ESP,20,3,25,5,44,47,4,6,...,1,24,83,31,24,10,21,94,1,tie
13,ESP,MNE,26,5,24,16,50,39,5,11,...,0,17,77,23,28,8,20,77,4,tie
14,FRA,SWE,21,11,36,24,56,34,17,4,...,0,22,75,31,18,8,27,84,1,first
15,SWE,FRA,18,13,34,13,32,25,12,3,...,1,26,90,32,55,20,34,96,3,second
16,DEN,RUS,20,7,23,15,75,39,21,5,...,0,24,81,21,30,12,28,78,1,first
17,RUS,DEN,15,6,28,6,62,33,23,6,...,0,25,94,27,39,29,32,84,3,second
18,CRO,ROU,16,7,49,12,41,32,20,4,...,0,17,72,20,10,7,20,92,4,first
19,ROU,CRO,14,6,30,8,30,34,12,6,...,2,28,96,25,33,15,42,98,3,second
20,NED,NOR,21,7,29,8,51,49,23,16,...,0,18,148,44,34,33,24,75,2,second
21,NOR,NED,35,9,36,14,59,40,44,15,...,0,22,105,28,34,15,23,81,1,first
22,HUN,GER,17,6,14,10,46,36,25,13,...,0,27,76,27,26,13,30,72,1,second
23,GER,HUN,15,12,24,12,32,27,22,14,...,0,13,80,24,23,11,25,79,4,first
24,CRO,NOR,16,7,49,12,41,32,20,4,...,0,18,148,44,34,33,24,75,2,second
25,NOR,CRO,35,9,36,14,59,40,44,15,...,2,28,96,25,33,15,42,98,3,first
26,NED,GER,21,7,29,8,51,49,23,16,...,0,27,76,27,26,13,30,72,1,first
27,GER,NED,15,12,24,12,32,27,22,14,...,0,22,105,28,34,15,23,81,1,second
28,HUN,ROU,17,6,14,10,46,36,25,13,...,0,17,72,20,10,7,20,92,4,first
29,ROU,HUN,14,6,30,8,30,34,12,6,...,0,13,80,24,23,11,25,79,4,second
30,NED,ROU,21,7,29,8,51,49,23,16,...,0,17,72,20,10,7,20,92,4,first
31,ROU,NED,14,6,30,8,30,34,12,6,...,0,22,105,28,34,15,23,81,1,second
32,CRO,GER,16,7,49,12,41,32,20,4,...,0,27,76,27,26,13,30,72,1,first
33,GER,CRO,15,12,24,12,32,27,22,14,...,2,28,96,25,33,15,42,98,3,second
34,HUN,NOR,17,6,14,10,46,36,25,13,...,0,18,148,44,34,33,24,75,2,second
35,NOR,HUN,35,9,36,14,59,40,44,15,...,0,13,80,24,23,11,25,79,4,first
36,RUS,NED,15,6,28,6,62,33,23,6,...,0,22,105,28,34,15,23,81,1,first
37,NED,RUS,21,7,29,8,51,49,23,16,...,0,24,81,21,30,12,28,78,1,second
38,FRA,CRO,21,11,36,24,56,34,17,4,...,2,28,96,25,33,15,42,98,3,first
39,CRO,FRA,16,7,49,12,41,32,20,4,...,1,26,90,32,55,20,34,96,3,second
40,NOR,DEN,35,9,36,14,59,40,44,15,...,0,25,94,27,39,29,32,84,3,first
41,DEN,NOR,20,7,23,15,75,39,21,5,...,0,18,148,44,34,33,24,75,2,second
42,CRO,DEN,16,7,49,12,41,32,20,4,...,0,25,94,27,39,29,32,84,3,first
43,DEN,CRO,20,7,23,15,75,39,21,5,...,2,28,96,25,33,15,42,98,3,second
44,FRA,NOR,21,11,36,24,56,34,17,4,...,0,18,148,44,34,33,24,75,2,second
45,NOR,FRA,35,9,36,14,59,40,44,15,...,1,26,90,32,55,20,34,96,3,first

In [27]:
X = train_df[match_features]
Y = train_df['result']
Y

0     second
1      first
2      first
3     second
4        tie
5        tie
6      first
7     second
8      first
9     second
10     first
11    second
12       tie
13       tie
14     first
15    second
16     first
17    second
18     first
19    second
20    second
21     first
22    second
23     first
24    second
25     first
26     first
27    second
28     first
29    second
30     first
31    second
32     first
33    second
34    second
35     first
36     first
37    second
38     first
39    second
40     first
41    second
42     first
43    second
44    second
45     first
Name: result, dtype: object

In [25]:
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical

encoder = LabelEncoder()
encoded_Y = encoder.fit_transform(Y)

onehot_Y = to_categorical(encoded_Y)
onehot_Y

array([[0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], dtype=float32)

In [52]:
from keras.models import Sequential
from keras.layers import Dense


# create model
model = Sequential()
model.add(Dense(32, input_dim=46, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(3, activation='softmax'))
# Compile model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [53]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_6 (Dense)              (None, 32)                1504
_________________________________________________________________
dense_7 (Dense)              (None, 16)                528
_________________________________________________________________
dense_8 (Dense)              (None, 8)                 136
_________________________________________________________________
dense_9 (Dense)              (None, 3)                 27
=================================================================
Total params: 2,195
Trainable params: 2,195
Non-trainable params: 0
_________________________________________________________________

In [33]:
#from keras.utils import plot_model
#plot_model(model, show_shapes=True)

In [54]:
model.fit(X, onehot_Y, epochs=20, batch_size=4)

Epoch 1/20
46/46 [==============================] - 0s 10ms/step - loss: 3.0838 - acc: 0.3696
Epoch 2/20
46/46 [==============================] - 0s 1ms/step - loss: 2.3937 - acc: 0.3913
Epoch 3/20
46/46 [==============================] - 0s 1ms/step - loss: 1.5381 - acc: 0.5435
Epoch 4/20
46/46 [==============================] - 0s 1ms/step - loss: 1.3009 - acc: 0.6304
Epoch 5/20
46/46 [==============================] - 0s 1ms/step - loss: 1.0938 - acc: 0.6739
Epoch 6/20
46/46 [==============================] - 0s 1ms/step - loss: 1.0711 - acc: 0.6304
Epoch 7/20
46/46 [==============================] - 0s 1ms/step - loss: 0.8740 - acc: 0.7609
Epoch 8/20
46/46 [==============================] - 0s 1ms/step - loss: 0.8176 - acc: 0.7174
Epoch 9/20
46/46 [==============================] - 0s 935us/step - loss: 0.7971 - acc: 0.7826
Epoch 10/20
46/46 [==============================] - 0s 935us/step - loss: 0.7130 - acc: 0.7174
Epoch 11/20
46/46 [==============================] - 0s 1ms/step - loss: 0.6735 - acc: 0.7826
Epoch 12/20
46/46 [==============================] - 0s 1ms/step - loss: 0.6685 - acc: 0.7609
Epoch 13/20
46/46 [==============================] - 0s 870us/step - loss: 0.6431 - acc: 0.8478
Epoch 14/20
46/46 [==============================] - 0s 1ms/step - loss: 0.6560 - acc: 0.7826
Epoch 15/20
46/46 [==============================] - 0s 1ms/step - loss: 0.6388 - acc: 0.7391
Epoch 16/20
46/46 [==============================] - 0s 1ms/step - loss: 0.6352 - acc: 0.8043
Epoch 17/20
46/46 [==============================] - 0s 1ms/step - loss: 0.6811 - acc: 0.7391
Epoch 18/20
46/46 [==============================] - 0s 1ms/step - loss: 0.6291 - acc: 0.8261
Epoch 19/20
46/46 [==============================] - 0s 1ms/step - loss: 0.6341 - acc: 0.7174
Epoch 20/20
46/46 [==============================] - 0s 1ms/step - loss: 0.5768 - acc: 0.8261

In [55]:
X_test = test_df[match_features]
Y_test = test_df['result']
encoded_Y_test = encoder.transform(Y_test)
encoded_Y_test

array([0, 0, 1, 1, 0, 0, 0, 0, 1, 2, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       2, 1])

In [56]:
y_pred = model.predict_classes(X_test)
y_pred

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 1], dtype=int64)

In [57]:
score = model.evaluate(X_test, to_categorical(encoded_Y_test))
score

24/24 [==============================] - 0s 3ms/step

[0.8529143929481506, 0.7916666865348816]

In [59]:
test_df['nn'] = encoder.inverse_transform(y_pred)
test_df[['result', 'nn']]

    result      nn
0    first   first
1    first   first
2   second   first
3   second  second
4    first   first
5    first   first
6    first   first
7    first   first
8   second  second
9      tie   first
10   first   first
11   first   first
12  second  second
13  second   first
14  second  second
15   first  second
16  second  second
17   first   first
18  second  second
19   first   first
20  second  second
21  second  second
22     tie   first
23  second  second